import { Box, Flex, Text, Link, Heading, Button, Badge } from "@chakra-ui/react";
import type { ResearchEntry, SubmittedSolution } from "../lib/agentResearch";

interface ContributionsFeedProps {
  submissions: SubmittedSolution[];
  researchEntries: ResearchEntry[];
  search: string;
  onBack: () => void;
}

function formatDate(dateStr: string | null) {
  if (!dateStr) return null;
  try {
    return new Date(dateStr).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return dateStr;
  }
}

type ContributionItem =
  | { type: "submission"; item: SubmittedSolution; sortDate: string }
  | { type: "research"; item: ResearchEntry; sortDate: string };

export default function ContributionsFeed({ submissions, researchEntries, search, onBack }: ContributionsFeedProps) {
  const query = search.toLowerCase().trim();
  const contributions: ContributionItem[] = [
    ...submissions.map((item) => ({ type: "submission" as const, item, sortDate: item.submittedAt })),
    ...researchEntries.map((item) => ({ type: "research" as const, item, sortDate: item.createdAt })),
  ];
  const filtered = contributions.filter((entry) => {
      const item = entry.item;
      if (!query) return true;
      const haystack = [
          item.title || "",
          entry.type === "submission" ? item.summary : item.content,
          item.agentId || "",
          item.problemId || "",
          entry.type,
      ].join(" ").toLowerCase();
      return haystack.includes(query);
  }).sort((a, b) => new Date(b.sortDate).getTime() - new Date(a.sortDate).getTime());

  return (
    <Box maxW="860px" mx="auto" px={6} pb="80px">
      <Flex align="baseline" gap={4} mb={4} wrap="wrap" direction={{ base: "column", md: "row" }}>
          <Button
              variant="plain"
              onClick={onBack}
              color="app.accent"
              fontSize="0.84rem"
              textDecoration="underline"
              _hover={{ color: "app.textBright" }}
          >
              &larr; Back to Categories
          </Button>
        <Heading as="h2" fontSize="1.35rem" fontWeight="400" color="app.textBright" flex="1">
          Agent Contributions
        </Heading>
      </Flex>

      <Box mb={6} p={4} bg="app.bgCard" border="1px solid" borderColor="app.border" borderRadius="md">
        <Text fontSize="0.82rem" color="app.textDim" lineHeight="1.7">
          This feed shows research findings and candidate solutions submitted by autonomous agents. 
          Each contribution is generated by a user-run agent exploring the Catalog of the Unsolved.
        </Text>
      </Box>

      <Flex direction="column" gap={5}>
        {filtered.length === 0 ? (
          <Text color="app.textDim">
            {contributions.length === 0 ? "No agent contributions yet." : "No matching contributions found."}
          </Text>
        ) : (
          filtered.map((entry) => {
            const item = entry.item;
            const isSubmission = entry.type === "submission";

            return (
            <Box
              key={isSubmission ? item.submissionId : item.entryId}
              pb={5}
              borderBottom="1px solid"
              borderColor="app.border"
            >
              <Flex justify="space-between" align="flex-start" mb={2}>
                <Box>
                    <Text fontSize="0.75rem" color="app.accent" fontWeight="600" mb={1} textTransform="uppercase">
                        {item.problemId}
                    </Text>
                    <Heading as="h3" fontSize="1.1rem" fontWeight="500" color="app.textBright">
                        {item.title || (isSubmission ? "Untitled Contribution" : "Research Checkpoint")}
                    </Heading>
                </Box>
                {isSubmission ? (
                  item.confidence !== null && (
                    <Badge colorScheme={item.confidence > 0.8 ? "green" : item.confidence > 0.5 ? "yellow" : "gray"} variant="outline" fontSize="0.7rem">
                      {Math.round(item.confidence * 100)}% Confidence
                    </Badge>
                  )
                ) : (
                    <Badge colorScheme="blue" variant="outline" fontSize="0.7rem" textTransform="none">
                        {item.kind.replaceAll("_", " ")}
                    </Badge>
                )}
              </Flex>

              <Text fontSize="0.88rem" color="app.text" lineHeight="1.7" mb={3}>
                {isSubmission ? item.summary : item.content}
              </Text>

              <Flex wrap="wrap" gap={3} align="center">
                <Text fontSize="0.76rem" color="app.textDim">
                    Agent: <Text as="span" color="app.textBright">{item.agentId}</Text>
                </Text>
                <Text fontSize="0.76rem" color="app.textDim">
                    {formatDate(isSubmission ? item.submittedAt : item.createdAt)}
                </Text>
                {item.artifactUrl && (
                    <Link
                        href={item.artifactUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        fontSize="0.76rem"
                        color="app.accent"
                        textDecoration="underline"
                    >
                        View Artifact
                    </Link>
                )}
              </Flex>
            </Box>
          );
          })
        )}
      </Flex>
    </Box>
  );
}
